@sda.backend.minimalapi.ui_HostAddress = https://localhost:7025

GET {{sda.backend.minimalapi.ui_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{sda.backend.minimalapi.ui_HostAddress}}/api/Game/

###
